branch-defaults:
  feature/redux:
    environment: employee-creator-backend
global:
  application_name: employee-creator
  branch: null
  default_ec2_keyname: null
  default_platform: ECS running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
