spring:
  datasource:
    url: jdbc:sqlserver://emplo-db-real.database.windows.net:1433;database=emplo-db;user=kabirt7@emplo-db-real;password=7VBYjueppbyN2dR;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: kabirt7
    password: 7VBYjueppbyN2dR
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
