name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
